#!/bin/bash
board=(0 1 2 3 4 5 6 7 8)
echo -n "is it integer? "
	
	read place
while [[ ! $place =~ ^[0-8]+$ ]]; do
	#echo ${board[$place]}
	echo -n "you cant go there, go somewhere else : "
	
	read place
done
	
	

 
