#!/bin/bash

board_display() {

echo "
	${board[0]} | ${board[1]} | ${board[2]}
	---------
	${board[3]} | ${board[4]} | ${board[5]}
	---------
	${board[6]} | ${board[7]} | ${board[8]}"

}



board=(0 1 2 3 4 5 6 7 8)
board_display
while [[ ${board[0]} == 0 || ${board[1]} == 1 || ${board[2]} == 2 || ${board[3]} == 3 || ${board[4]} == 4 ||${board[5]} == 5|| ${board[6]} == 6 || ${board[7]} == 7 || ${board[8]} == 8 ]]; do
	source ./ttt_p1
	player1

	board_display
	#is there a way to condense an expression?
	if [[ ${board[0]} == 0 || ${board[1]} == 1 || ${board[2]} == 2 || ${board[3]} == 3 || ${board[4]} == 4 ||${board[5]} == 5|| ${board[6]} == 6 || ${board[7]} == 7 || ${board[8]} == 8 ]]; then
		source ./ttt_p2
		player2

		board_display 
		continue
	fi
done
	echo "the board is filled"

	
	




