#!/bin/bash

board=(0 1 2 3 4 5 6 7 8)

echo "
	${board[0]} | ${board[1]} | ${board[2]}
	---------
	${board[3]} | ${board[4]} | ${board[5]}
	---------
	${board[6]} | ${board[7]} | ${board[8]}"

source ./ttt_p1
player1


echo "
	${board[0]} | ${board[1]} | ${board[2]}
	---------
	${board[3]} | ${board[4]} | ${board[5]}
	---------
	${board[6]} | ${board[7]} | ${board[8]}"

