#!/bin/bash

player2 () {

echo -ne "where do you want to go \e[92m\e[1mplayer 2\e[21m\e[39m? :  "
read place

while [[ ! $place =~ ^[0-8]+$ || ! ${board[$place]} =~ ^[0-8]+$ ]]; do
	
	echo -n "you cant go there, go somewhere else : "
	
	read place
	continue

		
done
	
board[$place]=o

}

 
