#!/bin/bash

player1 () {

echo -ne "where do you want to go \e[31m\e[1mPlayer 1\e[21m\e[39m ?:  "
read place
# good thing i figured out how || operator worked
while [[ ! $place =~ ^[0-8]+$ || ! ${board[$place]} =~ ^[0-8]+$ ]]; do
	
	echo -n "you cant go there, go somewhere else : "
	
	read place
	continue

		
done
	
	
board[$place]=x

}

 
