#!/bin/bash

player1 () {

echo -n "where do you want to go player 1? :  "
read place
# good thing i figured out how || operator worked
while [[ ! $place =~ ^[0-8]+$ || ! ${board[$place]} =~ ^[0-8]+$ ]]; do
	
	echo -n "you cant go there, go somewhere else : "
	
	read place
	continue

		
done
	
	
board[$place]=x

}

 
